---
title: "seurat integration"
output: html_notebook
---
```{r include=FALSE}
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(clustree)
library(reshape2)
library(PRROC)
library(WriteXLS)
library(rpart)
library(stringr)
library(rpart.plot)
library(cowplot)
library(EnhancedVolcano)
library(multtest)
library(metap)
library(presto)
library(tictoc)
suppressPackageStartupMessages(library(ComplexHeatmap))
library(ComplexHeatmap)
library(SeuratWrappers)
```

```{r}
paths = c('./Matrix Files/M/filtered_feature_bc_matrix/', './Matrix Files/F/filtered_feature_bc_matrix/')
raw_data = Read10X(paths)
sample_data = data.frame(matrix(data=NA, nrow=ncol(raw_data), ncol=1))
rownames(sample_data) <- colnames(raw_data)
colnames(sample_data) <- c("sex")

sample_data[grep("^1", rownames(sample_data)), "sex"] <- "M"
sample_data[grep("^2", rownames(sample_data)), "sex"] <- "F"

ser <- CreateSeuratObject(counts = raw_data, meta.data=sample_data)
table(ser@meta.data$sex)
```


```{r}
ser.list <- SplitObject(ser, split.by = "sex")
ser.list <- lapply(X = ser.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = ser.list, nfeatures=3000)
ser.list <- PrepSCTIntegration(object.list = ser.list, anchor.features = features)
```

```{r}
ser.anchors <- FindIntegrationAnchors(object.list = ser.list, normalization.method = "SCT", anchor.features = features)
ser.combined <- IntegrateData(anchorset = ser.anchors, normalization.method = "SCT")
```



```{r}
ser.combined <- RunPCA(ser.combined, npcs=30, verbose=F)

ser.combined <- RunUMAP(ser.combined, reduction="pca", dims=1:30)
ser.combined <- FindNeighbors(ser.combined, reduction="pca", dims = 1:30)
ser.combined <- FindClusters(ser.combined, resolution=0.1)
```



```{r fig.height=5, fig.width=5}
DimPlot(ser.combined, reduction="umap", label=TRUE)
DimPlot(ser.combined, reduction="umap", label=TRUE, group.by = "sex")
```

```{r}
markers <- RunPrestoAll(object = ser.combined, only.pos = TRUE, assay="integrated")
top5 <- markers %>% group_by(cluster) %>% top_n(5, avg_log2FC)
```
```{r fig.height=5, fig.width=15}
#VlnPlot(ser.combined, features = top5$gene, ncol = 10)+ NoLegend()
VlnPlot(ser.combined, features = top5$gene, ncol = 10, split.by = 'sex')+ NoLegend()
DotPlot(ser.combined, features = unique(top5$gene), split.by = "sex", cols = c("blue", "red")) + RotatedAxis()
DoHeatmap(subset(ser.combined, downsample=100), features = unique(top5$gene), angle=90, draw.lines = F) + scale_fill_gradient(low="white", high="red4")
#DoHeatmap(subset(ser.combined, downsample=100, subset=sex=="M"), features = unique(top5$gene), angle=90, draw.lines = F) + scale_fill_gradient(low="white", high="red4")
#DoHeatmap(subset(ser.combined, downsample=100, subset=sex=="F"), features = unique(top5$gene), angle=90, draw.lines = F) + scale_fill_gradient(low="white", high="red4")
```


```{r}
clus0_cons <- FindConservedMarkers(ser.combined, ident.1 = 0, grouping.var = "sex", only.pos=T, assay="RNA")
```


```{r}
cluster_markers <- rownames(clus0_cons %>% filter(M_avg_log2FC > 5, F_avg_log2FC > 5))
DotPlot(subset(ser.combined, downsample=100), features = cluster_markers) + RotatedAxis()
DoHeatmap(subset(ser.combined, downsample=100), features = cluster_markers, angle=90, draw.lines = F) + scale_fill_gradient(low="white", high="red4")
```


```{r}
VlnPlot(subset(ser.combined, downsample=100, idents=c(6, 7)), features = c("Il33", "Il7r", "Il4", "Il5", "Ifny", "Il13", "Il10"), split.by = "sex", cols = c("blue", "red")) + RotatedAxis()
```



```{r fig.height=5, fig.width=10}

genes_of_interest <- c("Ptprc", 
                       "Fcer1a", "Mcpt8", "Cd200r3", "Cpa3", "Gata2", #cluster 7 MCs and Basophils
                       "Ms4a4b", "Cd3e", "Cd3g", "Tcf7", "Trbc2", "Cd2",  #cluster 6 T cells
                       "Ltf", "Mmp9", "Lrg1", "Ngp", "Camp", #cluster 5 stage 1 neutrophils
                       "Olfm4", #cluster 4 OLFM4+ neutrophils
                       "Ebf1", "Cd19", "Cd79a", "Ly6d", "Mzb1", "Cd79b", #cluster 3 B cells
                       "Fn1", "F13a1", "Csf1r", "Adgre1", "Fcgr1", "Ccl2", #cluster 3 Monocytes Macrophages
                       "Ube2c", "Pclaf", "Birc5", "Top2a", "Plk1", #cluster 2 Tregs
                       "Clec4d", "Gm5150", "Jaml", "Pla2g7", "Il1b", #cluster 1 neutrophils
                       "Tcp11l2", "Trp53inp2", "Fmo5", "Tmem40", "Golim4"  #cluster 0 neutrophils
                       
)

DotPlot(ser.combined, features = unique(genes_of_interest)) + RotatedAxis()  
DoHeatmap(subset(ser.combined, downsample=100), assay="SCT", features = genes_of_interest, angle=90, draw.lines = F) + scale_fill_gradient(low="white", high="red4")
```




















